[package]
name = "hngxjsongetter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = "0.4.30"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
